[package]
authors = ["Ceri Storey <ceri@lshift.net>"]
name = "lmqueue"
version = "0.1.0"

[dependencies]
byteorder = "0.5.3"
clap = "2.10.2"
env_logger = "0.3.4"
error-chain = "0.5.0"
lmdb-zero = "0.1.0"
log = "0.3.6"

[dev-dependencies]
env_logger = "0.3.4"
quickcheck = "0.3.1"
tempdir = "0.3.5"
